#!/usr/bin/env bash

set -exo pipefail

DEPLOY_TOKEN="WTvPcYiim1W4322vpm9_"

if [[ -z "${DEPLOY_TOKEN}" ]]; then
    echo -e "\033[0;31mMissing DEPLOY_TOKEN, cannot release\033[0m"

    exit 1
fi

tag=${1:-$CI_COMMIT_TAG}

if [[ -z "${tag}" ]]; then
    echo -e "usage:\n\t$0 tag"

    exit 2
fi

api=${CI_API_V4_URL:-http://gitlab.idc.xiaozhu.com/api/v4}
runner_id=${CI_PROJECT_ID:-1428}

changelog="http://gitlab.idc.xiaozhu.com/$CI_PROJECT_PATH/blob/$tag/CHANGELOG.md"
sg="http://gitlab.idc.xiaozhu.com/$CI_PROJECT_PATH-downloads/raw/master/$tag"
release=$(cat <<EOS
{
    "name": "$tag",
    "tag_name": "$tag",
    "description": "See [the changelog]($changelog) :rocket:",
    "assets": {
        "links": [
            { "name": "linux amd64", "url": "$sg/binaries/$CI_PROJECT_NAME-linux-amd64" },
            { "name": "linux arm", "url": "$sg/binaries/$CI_PROJECT_NAME-linux-arm" },
            { "name": "macOS", "url": "$sg/binaries/$CI_PROJECT_NAME-darwin-amd64" }
        ]
    }
}
EOS
)

curl -f --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $DEPLOY_TOKEN" \
    --data "$release" --request POST "$api/projects/$runner_id/releases"
