.merge_request_pipelines:
  only:
    refs:
      - master
      - merge_requests
      - /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\Z/@$CI_PROJECT_PATH

.except_docs:
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /(^docs[\/-].*|.*-docs$)/

.efficacy_org_runner:
  tags:
    - efficacy-org
