.release:
  extends:
    - .except_docs
  stage: release
  before_script:
    - source ci/touch_make_dependencies
  tags:
    - release

.release_gitlab:
  extends:
    - .release
  script:
    - make release_upload
    - |
      # publish release on gitlab.idc.xiaozhu.com
      if [[ -n "${CI_COMMIT_TAG}" ]]; then
        ./ci/release_gitlab
      else
        echo -e "\033[0;31m****** gitlab publishing disabled ******\033[0m"
      fi

.release_stable:
  only:
    - tags
    - /\Av[0-9]+\.[0-9]+\.[0-9]+\Z/@$CI_PROJECT_PATH

stable gitlab:
  extends:
    - .release_gitlab
    - .release_stable
